allowBuilds:
  "@prisma/engines": true
  "@swc/core": true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - sharp
  - unrs-resolver
  - "@prisma/engines"
  - "@swc/core"
  - esbuild
  - prisma
